### ISSUE TITLE
zomb1 no t found

### ISSUE THREAD

**Issue by numpty9989** [kuplion/ExileZ-Mod#1]
I have added the files to the mission and getting zomb1 not found any ideas it's in the right directory and not touched the code that calls for the sound so have no clue... do you have any idea ??? an such with no sounds so don't know where they are and cant creep ppl out at 4 AM hahaha

**Comment by numpty9989** [comment]
NVM I fixed the issue it was my bad it said to add #inlcude somb.hpp and the file is zomb.cpp then i changed the line to cpp it worked

**Comment by kuplion** [comment]
You're not using ExileZ Mod if it's asking you to add stuff like that. I suspect you're using one of the old versions of ExileZ or another Zombie mod for Arma/Exile.

**Comment by numpty9989** [comment]
its possible but it works there r so many claiming to be the original exilez so its hard xD but  iwill be finbe now its working

**Comment by kuplion** [comment]
Use the files on this GitHub repo as right now you're posting issues to the wrong repo.
