### ISSUE TITLE
Removed Credits?

### ISSUE THREAD

**Issue by ravmustang** [kuplion/ExileZ-Mod#2]
Understandable that you wanted to rewrite this ExileZ.
Unfortunately you have removed credits from the original work.

Contributions made to the original code that you have copied and rereleased
Tanoa Trigger positions
Zombie Kill Stat in Kills 
Zombie Kill Stat in ZedKills
Zombie Rank Change

Unlike other people that demand changes made now or else bullshit.
We will allow 72 hours to pass before we will report this repo and thread on ExileMod Forums.

Violation: You did not include credits for my work as specified in the licensing terms.

The original work located here: https://github.com/patrix87/ExileZ-2
The original licensing you took this from: https://creativecommons.org/licenses/by-nc-sa/4.0/

All aspects of this repo have been recorded and saved for evidence in this case should the 72 hours lapse and you have not made the necessary changes as requested by the author.

**Comment by ravmustang** [comment]
Contributions and credits are as follows and required for the 72 hour deadline:

I Kuplion as part of Exile Mod staff, formally apologize to DonkeyPunch, DirtySanchez and RavMustang for my theft of their work without credits, for my slander of his character and my stupidity for yelling at community members in the discord over an @tag.

**Comment by kuplion** [comment]
All ORIGINAL authors credited. Stop being a cry baby.

**Comment by kuplion** [comment]
And actually compare the Tanoa Triggers, you ass. Mine were created by me, have an entirely different order, entirely different naming scheme, and entirely different coordinates.

But bless you for trying.. you were almost right; they are both for Tanoa, so well done you. Aren't you a clever boy, yes you are. Who's a clever boy. You are.
