### ISSUE TITLE
Copied from original author.

### ISSUE THREAD

**Issue by rcantec** [kuplion/ExileZ-Mod#3]
Original author found here -> https://github.com/patrix87/ExileZ-2

You removed credits from the original work. Contributions made to the original code that you have copied and re-released
The original licensing you took this from: [https://creativecommons.org/licenses/by-nc-sa/4.0/]

(https://creativecommons.org/licenses/by-nc-sa/4.0/)

Also the instructions on your page are WRONG

Should contain Place exilez.pbo in @ExileServer\addons
Add **"ryanzombies"** & "ryanzombiesfunctions" to the "addons" section of your mission.sqm

**Comment by kuplion** [comment]
The instructions are not wrong, you're just an ignorant prick. :)
