### ISSUE TITLE
You don't need this, as it's not needed. 

### ISSUE THREAD

**Issue by kupboss** [kuplion/ExileZ-Mod#4]
addOns[]= { "exile_client", "a3_map_altis", **"Ryanzombies", "ryanzombiesfunctions"**

For this copied addon to work it is only required to have addOns[]= { "exile_client", "a3_map_altis" 
unless you place the ryanzombies settings modules down in the mission.sqm and other modules that include the functions like the zombie spawner, but you don't know this because your a dumb-ass, and you don't know how to make missions or servers, you only know how to steal other peoples work, copy it and pretend to everyone that you created it, and then act like your the original maker, yet you're just a prick with no life and a shitty dating profile who gets off by treating people like shit in the Exile discord. Not only that I heard through the grape-vine your gay, a closet homo who likes dick. 
Good luck fuck face. BTW Go fuck yourself, fucking goof. Oh yes, don't trust anyone at Exile, they are all sharing info about you behind your back..... LMAO what a tool. BTW Friendlyplayer gayness is a shitty site, and your server's suck too!  
![download](https://user-images.githubusercontent.com/32610364/31315347-f0975bd4-abe4-11e7-9b88-4cee9a8b4549.png)

**Comment by kuplion** [comment]
lol
