### ISSUE TITLE
no zombies spawning.

### ISSUE THREAD

**Issue by Pesoen** [kuplion/ExileZ-Mod#5]
recently downloaded this, and the log shows it tries to spawn zombies. but it fails in doing so. any help?

this keeps showing in the logs.

`20:50:53 Cannot create non-ai vehicle RyanZombieB_Soldier_02_f_1medium,

20:50:53 "ExileZ Mod: Spawning 1 Zombie and adding it to the Monitor"`

i have tried altering settings, but so far nothing seems to work.

All steps on the forum and in the install guide has been followed, though step 7 gave me errors, and i therefore had to undo that to get the mission file to load.

**Comment by Pesoen** [comment]
gonna try that now, i should say i altered the default exile mission to add some things, and it changed the version from 12 to 53, and changed the structure of many things in the mission.sqm. that might have done it. gonna try both things, see if any of them work, will reply here with my findings.

**Comment by Pesoen** [comment]
original exile mission still complain with step 7.

Original mission file without step 7 will still not spawn zombies, same error as the original one, though the zombie names do cycle.

Pre-compiled pbo same error as before.

So it cannot find any zombies, or it is not allowed to spawn them. zombies can still be spawned using zeus, so they do work.

**Comment by kuplion** [comment]
Are you running RyanZombies on the clients and the server?

**Comment by Pesoen** [comment]
yup, required to join the server. and as stated, they do work, another zombie script was able to spawn them, though the did not attack players for some reason.

**Comment by kuplion** [comment]
Honestly no idea then. The PBO just works for everyone else and I've not encountered that error in all my testing.

Normally the *Cannot create non-ai vehicle* errors in Arma are from incorrect classnames.

**Comment by Pesoen** [comment]
interesting.. gonna try seeing if something is wrong somewhere with the names or something, the server has no battleye filters of any kind just yet..

is step 7 really that needed? its the only step i fail at regardless of what i try. could that possibly be the reason why it fails?

**Comment by Pesoen** [comment]
gonna try turning on debug, see if i can get any info from that.

**Comment by kuplion** [comment]
Step 7 isn't needed, but it's just good practice.

**Comment by Pesoen** [comment]
okay, good to know its likely not the one step that consistently fails that is the main cause..

could the reason be that its run on a linux arma 3 server? or should it work regardless of server OS?

**Comment by kuplion** [comment]
Yes, that will be the reason.

Open your @Zombies and Demons folder, and rename the Addons folder to addons (lowercase). That will fix it.

**Comment by Pesoen** [comment]
gonna try that now then, hope this works.

**Comment by Pesoen** [comment]
that fixed it, thanks for the help :) time to alter the config so i get the zombies just the way i want them to be, plenty of them, and scary as balls :P
